// Get characters
export const GET_PEOPLE = 'GET_PEOPLE';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';

// Get more characters
export const PAGINATE = 'PAGINATE';
export const PAGINATE_SUCCESS = 'PAGINATE_SUCCESS';

export const FILTER_ITEMS = 'FILTER_ITEMS';

export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';

export const FETCH_CHARACTER_PLANET = 'FETCH_CHARACTER_PLANET';
export const FETCH_CHARACTER_PLANET_SUCCESS =
  '  FETCH_CHARACTER_PLANET_SUCCESS';
